# Generated by Django 2.2.7 on 2019-12-01 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^.{36}$')]),
        ),
    ]
