# Generated by Django 2.2.7 on 2019-11-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('conversationId', models.CharField(max_length=36)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_bot', models.CharField(max_length=36)),
                ('to', models.CharField(max_length=36)),
                ('text', models.TextField()),
            ],
        ),
    ]
