# Generated by Django 2.2.7 on 2019-11-29 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0003_auto_20191129_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=36, primary_key=True, serialize=False),
        ),
    ]
