# Generated by Django 2.2.7 on 2019-12-01 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0006_auto_20191201_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='conversationId',
            field=models.CharField(max_length=36, validators=[django.core.validators.RegexValidator(code='nomatch', message='conversationId length has to be 36', regex='^.{36}$')]),
        ),
    ]
